name: React CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Установка зависимостей
        run: npm ci

      - name: Сборка проекта
        run: npm run build

      - name: Тестирование
        run: npm test -- --watchAll=false
